# Generated by Django 6.0 on 2025-12-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackexchangeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
