# Generated by Django 6.0 on 2025-12-26 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackexchangeapp', '0003_remove_question_votes_alter_question_asked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
    ]
