# Generated by Django 6.0.1 on 2026-01-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackexchangeapp', '0004_remove_answer_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
