# Generated by Django 6.0.1 on 2026-01-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackexchangeapp', '0005_alter_vote_vote_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_user_question_vote',
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_user_answer_vote',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('answer__isnull', True), ('question__isnull', False)), fields=('user', 'question'), name='unique_user_question_vote'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('answer__isnull', False), ('question__isnull', True)), fields=('user', 'answer'), name='unique_user_answer_vote'),
        ),
    ]
