# Generated by Django 6.0.1 on 2026-01-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackexchangeapp', '0006_remove_vote_unique_user_question_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(blank=True, choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4, null=True),
        ),
    ]
