# Generated by Django 6.0.1 on 2026-02-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackexchangeapp', '0007_alter_vote_vote_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
